In [50]:
# this is going to be new output preparation script 
import pandas as pd

Inv_cost_df = pd.read_excel(open("C:/Users/kar.eco/Downloads/example_output.xlsx", "rb"), sheet_name="Inv_cost", header=None)
report__node__stochastic_scenar_df = pd.read_excel(open("C:/Users/kar.eco/Downloads/example_output.xlsx", "rb"), sheet_name="report__node__stochastic_scenar", index_col=1)
report__node__stochastic_scenar_df = report__node__stochastic_scenar_df.drop(columns="Unnamed: 0")
Rolling_Horizons_df = pd.read_excel(open("C:/Users/kar.eco/Downloads/example_output.xlsx", "rb"), sheet_name="Rolling_Horizons", header=None)
Rolling_Horizons_df = Rolling_Horizons_df.iloc[1:].reset_index(drop=True)
Rolling_Horizons_df.columns = ['label', 'value']

In [51]:
Inv_cost_df

                        0         1  2  3             4       5   6     7
0             solar_plant  0.285714  0  1  5.833333e+04  12775D  35  0.02
1            electrolyzer  0.000000  0  1  8.375000e+06   9125D  25  0.02
2           co2_vaporizer  0.000000  0  1  2.083333e+06   7300D  20  0.02
3              dist_tower  0.000000  0  1  1.138889e+06  10950D  30  0.02
4           ch3oh_reactor  0.000000  0  1  1.333333e+00  10950D  30  0.02
5             steam_plant  0.000000  0  1  4.583333e+05   7300D  20  0.02
6            water_import  0.000000  0  1  2.882883e+04  10950D  30  0.02
7              co2_import  0.000000  0  1  0.000000e+00  10950D  30  0.02
8              wind_plant  0.000000  0  1  2.040741e+07  12775D  35  0.02
9          pth_dummy_unit  1.000000  0  1  0.000000e+00  10950D  30  0.02
10  excess_heat_exchanger  0.000000  0  1  1.083333e+06  10950D  30  0.02
11      dh_heat_exchanger  0.000000  0  1  0.000000e+00  10950D  30  0.04
12           o2_liquefier  0.000000  0  1  6.000000e+06  10950D  30  0.06
13                  h2_st  0.000000  0  1  2.666667e+06   9125D  25  0.02
14               ch3oh_st  0.000000  0  1  9.305788e+03   9125D  25  0.02
15               power_st  0.000000  0  1  1.508333e+06   9125D  25  0.02

In [52]:
report__node__stochastic_scenar_df

,Unnamed: 2,Report__ch3oh__realisation,Report__ch3oh_demand__realisation,Report__ch3oh_st__realisation,Report__co2__realisation,Report__excess_heat__realisation,Report__h2__realisation,Report__h2_st__realisation,Report__heat__realisation,Report__liquid_o2__realisation,Report__o2_node__realisation,Report__power__realisation,Report__power_st__realisation,Report__pth_dummy_node__realisation,Report__raw_ch3oh__realisation,Report__solar_plant_node__realisation,Report__steam__realisation,Report__vaporized_co2__realisation,Report__water__realisation,Report__wind_plant_node__realisation
2019-01-01T00:00:00,node_slack_neg,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-01-01T01:00:00,node_slack_neg,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-01-01T02:00:00,node_slack_neg,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-01-01T03:00:00,node_slack_neg,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2019-01-01T04:00:00,node_slack_neg,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-08-01T22:00:00,storages_invested,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-09-01T08:00:00,storages_invested,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-01T18:00:00,storages_invested,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-11-01T04:00:00,storages_invested,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-01T14:00:00,storages_invested,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
Rolling_Horizons = Rolling_Horizons_df.loc[Rolling_Horizons_df['label'] == 'total_costs', 'value'].values[0]
Rolling_Horizons

np.float64(12.0)

In [67]:
Storage_Investment_df = pd.DataFrame([],index=["Total share of max", "total_cost", "O&M"],columns=["methanol", "hydrogen", "power"])
Storage_Investment_df

                   methanol hydrogen power
Total share of max      NaN      NaN   NaN
total_cost              NaN      NaN   NaN
O&M                     NaN      NaN   NaN

In [68]:
sum(report__node__stochastic_scenar_df.loc[report__node__stochastic_scenar_df["Unnamed: 2"] == "storages_invested", "Report__ch3oh_st__realisation"])
sum(report__node__stochastic_scenar_df.loc[report__node__stochastic_scenar_df["Unnamed: 2"] == "storages_invested", "Report__h2_st__realisation"])
sum(report__node__stochastic_scenar_df.loc[report__node__stochastic_scenar_df["Unnamed: 2"] == "storages_invested", "Report__power_st__realisation"])

0.0

In [69]:
Storage_Investment_df

                   methanol hydrogen power
Total share of max      NaN      NaN   NaN
total_cost              NaN      NaN   NaN
O&M                     NaN      NaN   NaN